Task10/Models/DepositModel.cs
using System.ComponentModel.DataAnnotations;

namespace Task10.Models;

public class DepositModel
{
    [Required(ErrorMessage = "Поле Сумма вклада обязательно для заполнения.")]
    [Range(1, double.MaxValue, ErrorMessage = "Сумма вклада должна быть больше 1.")]
    public double InitialAmount { get; set; }

    [Required(ErrorMessage = "Поле Количество месяцев обязательно для заполнения.")]
    [Range(1, 60, ErrorMessage = "Количество месяцев должно быть в диапазоне от 1 до 60.")]
    public int NumberOfMonths { get; set; }
}

Task10/Controllers/BankApiController.cs
using Microsoft.AspNetCore.Mvc;
using Task10.Models;
using Task10.Services;

namespace Task10.Controllers;

// Используя веб апи в будущем можно добавить приложения для других платформ с таким же функционалом.
[Route("api/Bank")]
[ApiController]
public class BankApiController : ControllerBase
{
    private readonly DepositCalculatorService _depositCalculatorService;

    public BankApiController(DepositCalculatorService depositCalculatorService)
    {
        _depositCalculatorService = depositCalculatorService;
    }

    [HttpPost("CalculateDeposit")]
    public ActionResult<OperationResult<decimal>> CalculateDeposit(DepositModel depositModel)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(ModelState);
        }

        var result = _depositCalculatorService.CalculateFinalAmount(depositModel);
        return Ok(result);
    }
}

Task10/Controllers/BankController.cs
using Microsoft.AspNetCore.Mvc;
using Task10.Models;
using Task10.Services;
using static Task10.ViewDataConstants;

namespace Task10.Controllers;

public class BankController : Controller
{
    private readonly BankApiService _bankApiService;

    public BankController(BankApiService bankApiService)
    {
        _bankApiService = bankApiService;
    }

    [HttpPost]
    public async Task<IActionResult> CalculateDeposit(DepositModel depositModel)
    {
        if (!ModelState.IsValid)
        {
            return View("Index", depositModel);
        }

        var result = await _bankApiService.CalculateDepositAsync(depositModel);

        if (result.Success)
        {
            ViewData[FINAL_DEPOSIT_AMOUNT] = result.Data;
        }
        else
        {
            ModelState.AddModelError(string.Empty, result.ErrorMessage);
        }

        return View("Index", depositModel);
    }


    public IActionResult Index()
    {
        return View(null);
    }
}

Task10/Views/Bank/Index.cshtml
@model DepositModel;

@{
    ViewData["Title"] = "Bank Page";
}

<form asp-controller="Bank" asp-action="CalculateDeposit" method="post">
    <div class="form-group">
        <label for="InitialAmount">Сумма вклада:</label>
        <input min="1" type="number" step="any" asp-for="InitialAmount" class="form-control" placeholder="Введите сумму больше 1"/>
        <span asp-validation-for="InitialAmount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="NumberOfMonths">Количество месяцев:</label>
        <input min="1" max="60" type="number" asp-for="NumberOfMonths" class="form-control" placeholder="Введите количество месяцев (от 1 до 60)"/>
        <span asp-validation-for="NumberOfMonths" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Рассчитать</button>
</form>


<p class="final-deposit-amount">Конечная сумма вклада: @ViewData[FINAL_DEPOSIT_AMOUNT]</p>

Task10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Task10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Task10.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Bank" asp-action="Index">Task10</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Bank" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>


<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>